// Shared fixture-workspace builder for the sumkit examples.
//
// `sumkit` reports analyzer-summary cache coverage for a *tree of Dart
// projects*, and coverage is decided by each project's resolved dependencies —
// so every example needs a workspace where the projects (a) look like Dart
// packages to the traversal (they have a `pubspec.yaml`) and (b) have resolved
// dependency versions to classify (they have a `pubspec.lock`). This builder
// writes both, in a throwaway temp tree, and deletes it afterwards. That keeps
// every example hermetic and offline: nothing here runs `dart pub get`, talks
// to pub.dev, or invokes the analyzer.
//
// This is support code, not a concept example — hence the lower-cased,
// number-less name.
import 'dart:io';

/// Creates a temp workspace of **nested** Dart projects and returns its path:
///
///   <temp>/
///   ├── app/       app_runner    hosted: meta, collection, http   path: service_layer
///   ├── service/   service_layer hosted: meta, collection         path: data_layer
///   ├── data/      data_layer    hosted: meta
///   └── draft/     draft_pkg     pubspec.yaml only — NO pubspec.lock
///
/// The shape is chosen so each project says something different about caching:
///
///   * `data_layer` is a leaf: one cacheable dependency (`meta`), nothing else.
///     It is processed first in build order, so warming it seeds `meta` for the
///     projects that follow.
///   * `service_layer` shares `meta` with `data_layer` and adds `collection`;
///     it also has one **uncacheable** path dependency (`data_layer`).
///   * `app_runner` shares `meta` + `collection` and adds `http`; its path
///     dependency (`service_layer`) is likewise uncacheable. Because it depends
///     on the others it is processed last — by which point the shared
///     dependencies are already cached.
///   * `draft_pkg` has no `pubspec.lock` (its `dart pub get` has "not run"), so
///     a real generator could not analyse it yet. `sumkit` skips it.
///
/// Only `hosted` and `path` sources appear — deliberately no `sdk` source — so
/// resolution is fully deterministic without a Flutter SDK present.
///
/// The caller deletes the returned directory (see [disposeFixture]).
Future<Directory> createFixtureWorkspace() async {
  final root = await Directory.systemTemp.createTemp('sumkit_fixture_');

  await _writeProject(
    root,
    'data',
    pubspec: '''
name: data_layer
version: 1.0.0
description: Data access layer for the sample workspace.
environment:
  sdk: ^3.10.0
dependencies:
  meta: ^1.16.0
''',
    lock: _lock(const {
      'meta': _Hosted('1.16.0'),
    }),
  );

  await _writeProject(
    root,
    'service',
    pubspec: '''
name: service_layer
version: 1.2.0
description: Service layer for the sample workspace.
environment:
  sdk: ^3.10.0
dependencies:
  meta: ^1.16.0
  collection: ^1.19.1
  data_layer:
    path: ../data
''',
    lock: _lock(const {
      'collection': _Hosted('1.19.1'),
      'data_layer': _Path('1.0.0', '../data'),
      'meta': _Hosted('1.16.0'),
    }),
  );

  await _writeProject(
    root,
    'app',
    pubspec: '''
name: app_runner
version: 0.9.0
description: Runs the sample application by wiring the service layer together.
environment:
  sdk: ^3.10.0
dependencies:
  meta: ^1.16.0
  collection: ^1.19.1
  http: ^1.2.2
  service_layer:
    path: ../service
''',
    lock: _lock(const {
      'collection': _Hosted('1.19.1'),
      'http': _Hosted('1.2.2'),
      'meta': _Hosted('1.16.0'),
      'service_layer': _Path('1.2.0', '../service'),
    }),
  );

  // No pubspec.lock — `dart pub get` has "not run", so sumkit skips it.
  await _writeProject(
    root,
    'draft',
    pubspec: '''
name: draft_pkg
version: 0.0.1
description: A package whose dependencies have not been resolved yet.
environment:
  sdk: ^3.10.0
''',
  );

  return root;
}

/// Deletes a fixture workspace created by [createFixtureWorkspace].
Future<void> disposeFixture(Directory root) async {
  if (root.existsSync()) {
    await root.delete(recursive: true);
  }
}

/// Describes one locked package entry — just enough to render a `pubspec.lock`.
sealed class _LockEntry {
  const _LockEntry();
}

class _Hosted extends _LockEntry {
  const _Hosted(this.version);
  final String version;
}

class _Path extends _LockEntry {
  const _Path(this.version, this.relativePath);
  final String version;
  final String relativePath;
}

/// Renders a minimal but valid `pubspec.lock` for the given packages, in the
/// exact shape `DependencyResolver` parses (a `packages:` map keyed by name,
/// each with a `source`, a `version`, and a source-specific `description`).
String _lock(Map<String, _LockEntry> packages) {
  final buffer = StringBuffer('# Generated by pub (fixture)\npackages:\n');
  for (final entry in packages.entries) {
    final value = entry.value;
    buffer.writeln('  ${entry.key}:');
    buffer.writeln('    dependency: "direct main"');
    switch (value) {
      case _Hosted(:final version):
        buffer.writeln('    description:');
        buffer.writeln('      name: ${entry.key}');
        buffer.writeln('      url: "https://pub.dev"');
        buffer.writeln('    source: hosted');
        buffer.writeln('    version: "$version"');
      case _Path(:final version, :final relativePath):
        buffer.writeln('    description:');
        buffer.writeln('      path: "$relativePath"');
        buffer.writeln('      relative: true');
        buffer.writeln('    source: path');
        buffer.writeln('    version: "$version"');
    }
  }
  buffer.writeln('sdks:');
  buffer.writeln('  dart: ">=3.10.0 <4.0.0"');
  return buffer.toString();
}

Future<void> _writeProject(
  Directory root,
  String folder, {
  required String pubspec,
  String? lock,
}) async {
  final dir = Directory('${root.path}/$folder');
  await dir.create(recursive: true);
  await File('${dir.path}/pubspec.yaml').writeAsString(pubspec);
  if (lock != null) {
    await File('${dir.path}/pubspec.lock').writeAsString(lock);
  }
}
