// sce38: the pub-cache pre-flight has to be reachable from the tools that
// actually read resolved package sources, not only from the test runner.
//
// `PubCacheIntegrity` landed with `checkProject` + `describe`, and exactly one
// caller — testkit. The sighting that motivated it was an AOT compile, where
// a package missing from the cache surfaces as `Bad state: Generating AOT
// kernel dill failed!` from inside the compiler and names nothing. These tests
// cover the two shared entry points that let a call site be an `if`:
// `PubCacheIntegrity.preflight` for any tool, and
// `CommandExecutor.pubCachePreflight` for a buildkit-style executor.
//
// Every test injects a fake cache via `pubCachePath`, so none of them can be
// perturbed by the state of the real `~/.pub-cache`.

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:tom_build_base/tom_build_base_v2.dart';

/// Writes `<root>/hosted/<host>/<name>-<version>/pubspec.yaml`.
void cachePackage(Directory cacheRoot, String name, String version) {
  final dir = Directory(
    p.join(cacheRoot.path, 'hosted', 'pub.dev', '$name-$version'),
  )..createSync(recursive: true);
  File(
    p.join(dir.path, 'pubspec.yaml'),
  ).writeAsStringSync('name: $name\nversion: $version\n');
}

/// A project whose lock names each of [hosted].
Directory projectLocking(Map<String, String> hosted) {
  final dir = Directory.systemTemp.createTempSync('pcpf_proj_');
  File(p.join(dir.path, 'pubspec.yaml')).writeAsStringSync('name: zom_pcpf\n');
  final buffer = StringBuffer('# Generated by pub\npackages:\n');
  hosted.forEach((name, version) {
    buffer.write(
      '  $name:\n'
      '    dependency: "direct main"\n'
      '    description:\n'
      '      name: $name\n'
      '      sha256: "0000"\n'
      '      url: "https://pub.dev"\n'
      '    source: hosted\n'
      '    version: "$version"\n',
    );
  });
  buffer.write('sdks:\n  dart: ">=3.0.0 <4.0.0"\n');
  File(p.join(dir.path, 'pubspec.lock')).writeAsStringSync(buffer.toString());
  return dir;
}

/// An executor that reports what the pre-flight told it, so the base-class
/// helper is exercised through the surface a real executor uses.
class _ProbeExecutor extends CommandExecutor {
  _ProbeExecutor(this.cachePath);

  final String cachePath;

  @override
  Future<ItemResult> execute(CommandContext context, CliArgs args) async {
    final preflight = pubCachePreflight(context, pubCachePath: cachePath);
    if (preflight != null) return preflight;
    return ItemResult.success(
      path: context.path,
      name: context.name,
      message: 'compiled',
    );
  }
}

void main() {
  late Directory cache;
  final temps = <Directory>[];

  Directory temp(Directory d) {
    temps.add(d);
    return d;
  }

  setUp(() {
    cache = temp(Directory.systemTemp.createTempSync('pcpf_cache_'));
  });

  tearDownAll(() {
    for (final d in temps) {
      try {
        d.deleteSync(recursive: true);
      } catch (_) {}
    }
  });

  Future<ItemResult> runProbe(Directory project) =>
      _ProbeExecutor(cache.path).execute(
        CommandContext(
          fsFolder: FsFolder(path: project.path),
          natures: const [],
          executionRoot: project.path,
        ),
        const CliArgs(),
      );

  group('PubCacheIntegrity.preflight', () {
    test('BB-PCPF-1: returns null when the cache supplies every locked package '
        '[2026-09-18] (PASS)', () {
      final project = temp(projectLocking({'tom_d4rt': '1.29.0'}));
      cachePackage(cache, 'tom_d4rt', '1.29.0');

      expect(
        PubCacheIntegrity.preflight(
          projectPath: project.path,
          pubCachePath: cache.path,
        ),
        isNull,
        reason: 'nothing is missing, so there is nothing to stop for',
      );
    });

    test('BB-PCPF-2: names the missing package, its location and the repair '
        '[2026-09-18] (PASS)', () {
      // The control: one package present, one absent. A helper that reported
      // unconditionally would pass BB-PCPF-2 while failing BB-PCPF-1, and a
      // helper that reported nothing would pass BB-PCPF-1 while failing this
      // one — so the pair pins the behaviour from both sides.
      final project = temp(
        projectLocking({'tom_d4rt': '1.29.0', 'present_pkg': '2.0.0'}),
      );
      cachePackage(cache, 'present_pkg', '2.0.0');

      final report = PubCacheIntegrity.preflight(
        projectPath: project.path,
        pubCachePath: cache.path,
      );

      expect(report, isNotNull);
      expect(report, contains('tom_d4rt'));
      expect(report, contains('1.29.0'));
      expect(
        report,
        contains('dart pub get'),
        reason: 'a report without the repair leaves the reader stuck',
      );
      expect(
        report,
        isNot(contains('present_pkg')),
        reason: 'a package the cache can supply is not a finding',
      );
    });

    test(
      'BB-PCPF-3: an unresolved project is not a finding [2026-09-18] (PASS)',
      () {
        // No lock at all means nothing is locked, so nothing can be missing
        // from the cache. Reporting here would fire on every fresh checkout.
        final dir = temp(Directory.systemTemp.createTempSync('pcpf_nolock_'));
        File(
          p.join(dir.path, 'pubspec.yaml'),
        ).writeAsStringSync('name: zom_pcpf\n');

        expect(
          PubCacheIntegrity.preflight(
            projectPath: dir.path,
            pubCachePath: cache.path,
          ),
          isNull,
        );
      },
    );
  });

  group('CommandExecutor.pubCachePreflight', () {
    test('BB-PCPF-4: lets the executor do its work when the cache is complete '
        '[2026-09-18] (PASS)', () async {
      final project = temp(projectLocking({'tom_d4rt': '1.29.0'}));
      cachePackage(cache, 'tom_d4rt', '1.29.0');

      final result = await runProbe(project);

      expect(result.success, isTrue);
      expect(
        result.message,
        'compiled',
        reason:
            'the pre-flight must not stand between a good project and '
            'the work it asked for',
      );
    });

    test('BB-PCPF-5: stops the executor with a failure naming the package '
        '[2026-09-18] (PASS)', () async {
      final project = temp(projectLocking({'tom_d4rt': '1.29.0'}));
      // Deliberately not cached.

      final result = await runProbe(project);

      expect(
        result.success,
        isFalse,
        reason:
            'this is the case that otherwise dies inside the AOT '
            'compiler with Bad state: Generating AOT kernel dill failed!',
      );
      expect(result.error, contains('tom_d4rt'));
      expect(
        result.message,
        isNot('compiled'),
        reason: 'the executor must not have proceeded to its real work',
      );
    });

    test('BB-PCPF-6: the failure carries the full report, not just a mention '
        '[2026-09-18] (PASS)', () async {
      final project = temp(projectLocking({'tom_d4rt': '1.29.0'}));

      final result = await runProbe(project);

      expect(result.error, contains('expected:'));
      expect(result.error, contains('repair:'));
      expect(
        result.error,
        contains('NOT an API change'),
        reason: 'the whole point is to pre-empt the Undefined-name misread',
      );
    });
  });
}
