// scd8_aicx: a locked package missing from the pub cache must be named as
// such, not left to surface as a compile error.
//
// A hosted package whose `pubspec.lock` entry has no directory in the cache
// produces no resolution error at all. `dart pub get` reports success — the
// lock is satisfiable — and the failure lands later as `Error: Undefined name
// '<Symbol>'` at every use site, followed by `AOT compilation failed`. The
// symptom points at the source file that uses the symbol, so the natural
// reading is that the identifier was renamed upstream; the actual cause is one
// directory missing on disk. Nothing in the compiler's output mentions the
// cache, and the misreading is deterministic rather than careless — twice in
// one session, for `tom_build_base-2.7.1` and `tom_d4rt-1.29.0`.
//
// These tests build a fake cache so each shape is exercised without touching
// the real `~/.pub-cache`: a package whose directory is gone, one whose
// directory exists but holds no `pubspec.yaml` (pub treats that as installed
// and walks straight past it), and the sources that are none of this check's
// business.

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:tom_build_base/tom_build_base.dart';

/// Writes `<root>/hosted/<host>/<name>-<version>/pubspec.yaml`.
void cachePackage(
  Directory cacheRoot,
  String name,
  String version, {
  String host = 'pub.dev',
  bool withPubspec = true,
}) {
  final dir = Directory(p.join(cacheRoot.path, 'hosted', host, '$name-$version'))
    ..createSync(recursive: true);
  if (withPubspec) {
    File(p.join(dir.path, 'pubspec.yaml'))
        .writeAsStringSync('name: $name\nversion: $version\n');
  }
}

/// A `pubspec.lock` naming [hosted] packages plus one of every other source.
String lockFile(Map<String, String> hosted, {String host = 'https://pub.dev'}) {
  final buffer = StringBuffer('# Generated by pub\npackages:\n');
  hosted.forEach((name, version) {
    buffer.write('  $name:\n'
        '    dependency: "direct main"\n'
        '    description:\n'
        '      name: $name\n'
        '      sha256: "0000"\n'
        '      url: "$host"\n'
        '    source: hosted\n'
        '    version: "$version"\n');
  });
  buffer.write('  a_path_dep:\n'
      '    dependency: "direct main"\n'
      '    description:\n'
      '      path: "../somewhere"\n'
      '      relative: true\n'
      '    source: path\n'
      '    version: "1.0.0"\n');
  buffer.write('  flutter:\n'
      '    dependency: "direct main"\n'
      '    description: flutter\n'
      '    source: sdk\n'
      '    version: "0.0.0"\n');
  buffer.write('sdks:\n  dart: ">=3.0.0 <4.0.0"\n');
  return buffer.toString();
}

/// A project directory holding [lock] as its `pubspec.lock`.
Directory projectWithLock(String lock) {
  final dir = Directory.systemTemp.createTempSync('pci_proj_');
  File(p.join(dir.path, 'pubspec.yaml')).writeAsStringSync('name: zom_pci\n');
  File(p.join(dir.path, 'pubspec.lock')).writeAsStringSync(lock);
  return dir;
}

void main() {
  late Directory cache;
  final temps = <Directory>[];

  Directory temp(Directory d) {
    temps.add(d);
    return d;
  }

  setUp(() {
    cache = temp(Directory.systemTemp.createTempSync('pci_cache_'));
  });

  tearDownAll(() {
    for (final d in temps) {
      try {
        d.deleteSync(recursive: true);
      } catch (_) {}
    }
  });

  group('PubCacheIntegrity', () {
    test(
      'BB-PCI-1: a cache holding every locked package reports nothing '
      '[2026-09-12]',
      () {
        cachePackage(cache, 'ansicolor', '2.0.3');
        cachePackage(cache, 'utopia_tui', '1.1.1');
        final project = temp(projectWithLock(
          lockFile({'ansicolor': '2.0.3', 'utopia_tui': '1.1.1'}),
        ));

        final problems = PubCacheIntegrity.checkProject(
          projectPath: project.path,
          pubCachePath: cache.path,
        );

        expect(problems, isEmpty);
      },
    );

    test(
      'BB-PCI-2: a locked package with no directory is reported with its '
      'version and the path that should hold it [2026-09-12]',
      () {
        cachePackage(cache, 'ansicolor', '2.0.3');
        final project = temp(projectWithLock(
          lockFile({'ansicolor': '2.0.3', 'utopia_tui': '1.1.1'}),
        ));

        final problems = PubCacheIntegrity.checkProject(
          projectPath: project.path,
          pubCachePath: cache.path,
        );

        expect(problems, hasLength(1));
        final problem = problems.single;
        expect(problem.package, 'utopia_tui');
        expect(problem.version, '1.1.1');
        expect(problem.kind, PubCacheProblemKind.missingDirectory);
        expect(problem.expectedPath, contains('utopia_tui-1.1.1'));
      },
    );

    test(
      'BB-PCI-3: a directory without a pubspec.yaml is reported too — pub '
      'treats it as installed [2026-09-12]',
      () {
        cachePackage(cache, 'ansicolor', '2.0.3', withPubspec: false);
        final project =
            temp(projectWithLock(lockFile({'ansicolor': '2.0.3'})));

        final problems = PubCacheIntegrity.checkProject(
          projectPath: project.path,
          pubCachePath: cache.path,
        );

        expect(problems, hasLength(1));
        expect(problems.single.kind, PubCacheProblemKind.missingPubspec);
        expect(
          problems.single.remedy,
          contains('rm -rf'),
          reason:
              'pub walks past a directory that exists, so `dart pub get` '
              'alone does not repair this shape — the directory has to go '
              'first',
        );
      },
    );

    test(
      'BB-PCI-4: path, sdk and git sources are not this check\'s business '
      '[2026-09-12]',
      () {
        // The lock always carries a path dep and an sdk dep; neither lives in
        // the cache, and a missing one fails loudly on its own terms.
        final project = temp(projectWithLock(lockFile(const {})));

        expect(
          PubCacheIntegrity.checkProject(
            projectPath: project.path,
            pubCachePath: cache.path,
          ),
          isEmpty,
        );
      },
    );

    test(
      'BB-PCI-5: a package cached under a differently spelled host directory '
      'still counts as present [2026-09-12]',
      () {
        // Pub encodes non-default hosts into the directory name; the encoding
        // is pub's business, so presence is decided by finding the package,
        // not by reproducing the spelling.
        cachePackage(cache, 'inhouse_pkg', '0.1.0', host: 'pub.example.com%47x');
        final project = temp(projectWithLock(
          lockFile(
            {'inhouse_pkg': '0.1.0'},
            host: 'https://pub.example.com/x',
          ),
        ));

        expect(
          PubCacheIntegrity.checkProject(
            projectPath: project.path,
            pubCachePath: cache.path,
          ),
          isEmpty,
        );
      },
    );

    test(
      'BB-PCI-6: a project that has not resolved yet reports nothing '
      '[2026-09-12]',
      () {
        final dir = temp(Directory.systemTemp.createTempSync('pci_nolock_'));
        File(p.join(dir.path, 'pubspec.yaml'))
            .writeAsStringSync('name: zom_pci\n');

        expect(
          PubCacheIntegrity.checkProject(
            projectPath: dir.path,
            pubCachePath: cache.path,
          ),
          isEmpty,
          reason: 'nothing is resolved, so nothing can be missing from it',
        );
      },
    );

    test(
      'BB-PCI-7: the report names the package, the path and what to do — the '
      'compiler error says none of it [2026-09-12]',
      () {
        final project = temp(projectWithLock(lockFile({'utopia_tui': '1.1.1'})));
        final problems = PubCacheIntegrity.checkProject(
          projectPath: project.path,
          pubCachePath: cache.path,
        );

        final report = PubCacheIntegrity.describe(problems);
        expect(report, contains('utopia_tui'));
        expect(report, contains('1.1.1'));
        expect(report, contains(cache.path));
        expect(report.toLowerCase(), contains('pub cache'));
        expect(report, contains('dart pub get'));
      },
    );

    test(
      'BB-PCI-8: PUB_CACHE decides where the cache is [2026-09-12]',
      () {
        cachePackage(cache, 'ansicolor', '2.0.3');
        final project =
            temp(projectWithLock(lockFile({'ansicolor': '2.0.3'})));

        // Resolved from the environment rather than passed in: the same cache
        // is found, so the package reads as present.
        expect(
          PubCacheIntegrity.checkProject(
            projectPath: project.path,
            environment: {'PUB_CACHE': cache.path},
          ),
          isEmpty,
        );
        // And with the environment pointing somewhere empty, it does not.
        final empty = temp(Directory.systemTemp.createTempSync('pci_empty_'));
        expect(
          PubCacheIntegrity.checkProject(
            projectPath: project.path,
            environment: {'PUB_CACHE': empty.path},
          ),
          hasLength(1),
        );
      },
    );
  });
}
